services:
  app:
    build: .
    image: topnews_app
    volumes:
      - .:/topnews
      - ruby_gems:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  chrome:
    image: selenium/standalone-chrome:latest # this version should match that of the selenium-webdriver gem (see Gemfile)
    volumes:
      - /dev/shm:/dev/shm
    profiles:
      - test

  app_test:
    build: .
    image: topnews_app
    volumes:
      - .:/topnews
      - ruby_gems:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      - HUB_URL=http://chrome:4444/wd/hub
    depends_on:
      - db
      - chrome
    profiles:
      - test

volumes:
  ruby_gems:
